import './App.css';
import Box from './Box'

var lis = [
'The_Thrust_Boys_Song(MP3160K).mp3',
'The_Weeknd_-_Starboy_ft._Daft_Punk_(Official_Video)(MP3160K).mp3',
'Tujhse_Naraz_Nahi_Zindagi_Female_Cover_Sanam_Lata_Mangeshkar_Hits_Old_Hindi_Songs_version(MP3_160K).mp3',
'7G_Rainbow_Colony_them_music_yuvan_hits(MP3160K).mp3',
'A.R._Rahman_-_Raanjhanaa_Best_Lyric_VideoSonam_KapoorDhanush_Jaswinder_Shiraz(MP3_160K).mp3',
'AURORA_-_Runaway(MP3160K).mp3',
'Aasman_Ko_Chukar(MP3160K).mp3',
'Akon_-_Right_Now_(Na_Na_Na)_(Official_Video)(MP3160K).mp3',
'AmmaAmmaNeeVennela_Full_Video_Song_Paagal_Songs___Vishwak_Sen___Naressh_Kuppili___Radhan(MP3_160K).mp3',
'Aqua_-_Barbie_Girl_(Official_Music_Video)(MP3160K).mp3',
'Arjun_Reddy_Love_BGM_----_Perfect_Piano_Notes_Sonu_Rathod(MP3_160K).mp3',
'Axel_Thesleff_-_Bad_Karma_[Bass_Boosted](MP3160K).mp3',
'Aya_Nakamura_-_Copines_(Lyrics)(MP3160K).mp3',
'BAARISHEIN_(Studio)_Anuv_Jain(MP3160K).mp3',
'Boney_M._-_Rasputin_(lyrics)(MP3160K).mp3',
'Bruno_Mars_-_Thats_What_I_Like_[Official_Music_Video](MP3160K).mp3',
'Busta_Rhymes_-_Touch_It_(Deep_Remix)_AMG_Showtime_TikTok(MP3_160K).mp3',                            'Chammak_Challo_X_Drake_Mashup_Shahrukh_Khan_Drake_Akon_TikTok_Remix_revibe_Trappodu(MP3_160K).mp3',
'Chand_Sifarish_Full_Song_Fanaa___Aamir_Khan__Kajol___Shaan__Kailash_Kher___Jatin-Lalit___Prasoon(MP3_160K).mp3',
'Chura_Liya_Hai_Tumne_Jo_Dil_Ko_4K_Video_Yaadon_Ki_Baaraat___Zeenat_A__Mohammed_Rafi__Asha_Bhosle(MP3_160K).mp3',
'Ckay_-_Love_Nwantiti_song_instrumental_cover_on_Walk_Band(MP3160K).mp3',
'Coke_Studio_Season_14_Pasoori___Ali_Sethi_x_Shae_Gill(MP3_160K).mp3',
'Coldplay_-_Hymn_For_The_Weekend_(Official_Video)(MP3160K).mp3',
'DEKHA_EK_KHWAB_LOFI_CHILL_MIX_DJ_LNS(MP3_160K).mp3',
'Dandelions(MP3160K).mp3',
'Dharia_-_Sugar_Brownies_(by_Monoir)_[Official_Video](MP3160K).mp3',
'Dua_Lipa_DaBaby_-_Levitating_(Lyrics)_you_want_me_i_want_you_baby(MP3_160K).mp3',
'Duniya_(slowed_reverb)(MP3160K).mp3',
'Eega_Video_Songs_-_Konchem_Konchem_Song_-_Vel_Records(MP3160K).mp3',
'Ellie_Goulding_-_Love_Me_Like_You_Do_(Official_Video)(MP3160K).mp3',
'Emai_Poyave_Full_Video_Padi_Padi_Leche_Manasu_Sharwanand__Sai_Pallavi___Vishal_Chandrashekar(MP3_160K).mp3',
'Eminem_-_Love_The_Way_You_Lie_ft._Rihanna(MP3160K).mp3',
'Fairytale(MP3160K).mp3',
'Flo_Rida_-_Low_ft._T-Pain_[Apple_Bottom_Jeans]_(Lyrics)(MP3160K).mp3',
'Future_-_Mask_Off_(Official_Music_Video)(MP3160K).mp3',
'Glass_Animals_-_Heat_Waves_(Official_Video)(MP3160K).mp3',
'Gunzukunnaa(MP3160K).mp3',
'Gym_Class_Heroes_Stereo_Hearts_ft._Adam_Levine_[OFFICIAL_VIDEO](MP3160K).mp3',
'Ha_Mhara_Ho_Mhara_Ho_Mhara_Mithoda_Mehman_Bhala_Aaviya_Ha_Mhara_Pardesi_Mehman_Bhala_Aaviya_(Lyrics)(MP3160K).mp3',
'Halamithi_Habibo_(Telugu)_-_Lyric_Video_Beast_Thalapathy_Vijay___Sun_Pictures___Nelson___Anirudh(MP3_160K).mp3',
'Hosanna_-_Vinnaithandi_Varuvaya_EASY_TO_PLAY_Keyboard_Notes___A.R.Rahman_(Notes_in_description)(MP3_160K).mp3',
'ITS_TIME_TO_GO_BEAST_MODE_(BASS_BOOSTED)(MP3160K).mp3',
'Imagine_Dragons_x_J.I.D_-_Enemy_(from_the_series_Arcane_League_of_Legends)(MP3160K).mp3',
'Inthandham_Lyrical_Video_Song_-_Sita_Ramam_(Telugu)_Dulquer_Mrunal___Vishal___Hanu_Raghavapudi(MP3_160K).mp3',
'Jaymes_Young_-_Infinity_[Official_Audio](MP3160K).mp3',
'Jetta_-_Id_Love_To_Change_The_World_(Matstubs_Remix)_[Official_Video](MP3160K).mp3',
'Jitni_Tu_Milti_Jaye_Utni_Lage_Thodi_Thodi_(Official_Video)_New_Version_Song_T-Series_Records(MP3160K).mp3',
'Joel_Adams_-_Please_Dont_Go_(Lyrics)(MP3160K).mp3',
'Joker_singer_Pakistani_street_talent_KALA_BANDAR_by_Ahmed_khan(MP3_160K).mp3',
'KURANG_SEXY_(LIBERTARIA_REMIX)_-_SOIMAH_PANCAWATI(MP3160K).mp3',
'Kaleshi_Chori_(Video)_Pranjal_Dahiya_DG_IMMORTALS_Raga__Harjas__Virtual_AF__Sshiv___Deepesh_Goyal(MP3_160K).mp3',
'Khatta_Meetha_Movie_Sajde_Video_Song____Akshay_Kumar__Trisha____Eagle_Music(MP3_160K).mp3',
'Kina_-_Can_We_Kiss_Forever_(Lyrics)_ft._Adriana_Proenza(MP3160K).mp3',
'Kya_mujhe_pyar_hai_(Tum_Kyu_Chale_Aate_Ho)_-_Slow_And_Reverb(MP3160K).mp3',
'LYRICAL_Maa_(Song)_Taare_Zameen_Par___Aamir_Khan__Darsheel_Safary___Shankar_Mahadevan(MP3_160K).mp3',
'La_casa_de_papel_Soundtrack_Cecilia_Krull_-_My_life_is_going_on_(Lyric_Video)(MP3160K).mp3',
'Let_Me_Down_Slowly_x_Main_Dhoondne_Ko_Zamaane_Mein_(Gravero_Mashup)_Full_Version(MP3160K).mp3',
'Lil_Nas_X_-_Old_Town_Road_(Official_Video)_ft._Billy_Ray_Cyrus(MP3160K).mp3',
'Love_You_Zindagi_(From_Dear_Zindagi)(MP3_160K).mp3',
'Love_Your_Voice(MP3160K).mp3',
'MIDDLE_OF_THE_NIGHT.mp3',
'Maine_Royaan_LofiRemix__Tanveer_Evan(MP3_160K).mp3',
'Mark_Ronson_-_Uptown_Funk_(Official_Video)_ft._Bruno_Mars(MP3160K).mp3',
'Melanie_Martinez_-_Play_Date_[Official_Lyric_Video](MP3160K).mp3',
'Naa_Kosam_-_Full_Video_Bangarraju_Naga_Chaitanya___Krithi_Shetty___Anup_Rubens___Sid_Sriram(MP3_160K).mp3',
'Nachdi_Phira(MP3160K).mp3',
'Neethoney_Dance_Full_Video_Song_Dhruva_Full_Video_Songs_Ram_Charan_Rakul_Preet___HipHopTamizha(MP3_160K).mp3',
'Nelly_-_Gone_ft._Kelly_Rowland_(Official_Video)(MP3160K).mp3',
'One_Direction_-_Night_Changes_(Lyrics)(MP3160K).mp3',
'Pehla_Nasha_-_Udit_Narayan_(Slowed_Reverb)_Retro_Week(MP3160K).mp3',
'Powfu_-_death_bed_(coffee_for_your_head)_(Official_Video)_ft._beabadoobee(MP3160K).mp3',
'Prema_Santosham_Full_Video_Song_Surya_Vs_Surya_Video_Songs____Nikhil_Trida_Chowdary(MP3_160K).mp3',
'RANDALL_-_Wahran_(Official_Audio)(MP3160K).mp3',
'Rema_-_Calm_Down_(Official_Music_Video)(MP3160K).mp3',
'Rick_Astley_-_Never_Gonna_Give_You_Up_(Official_Music_Video)(MP3160K).mp3',
'Rosa_Linn_-_Snap_-_(Official_Eurovision_Music_Video)(MP3160K).mp3',
'Safari(MP3160K).mp3',
'Secret_website_you_didnt_know_exists_pt1_(shorts)(MP3_160K).mp3',
'Sia_-_Chandelier_(Official_Video)(MP3160K).mp3',
'Sirivennela_-_Full_Video_Song_Shyam_Singha_Roy_Nani__Sai_Pallavi___Mickey_J_Meyer(MP3_160K).mp3',
'Snap_x_Baarishen_-_Mashup_(Full_Version)_Gravero_TP(MP3_160K).mp3',
'Star_Wars_-_Imperial_March_(Goblins_from_Mars_Trap_Remix)(MP3160K).mp3',
'Stephen_Sanchez_Em_Beihold_-_I_would_rather_die_than_let_you_go_(Until_I_Found_You)_(Lyrics)(MP3160K).mp3',
'Surili_Akhiyon_Wale_(Video_Song)_-_Veer(MP3160K).mp3',
'Taylor_Swift_-_Blank_Space(MP3160K).mp3',
'Telusa_Telusa_Video_Song_Sarrainodu_Video_Songs_Allu_Arjun_Rakul_Preet___SS_Thaman__Telugu_Songs(MP3_160K).mp3',
'Tera_Ghata_Gajendra_Verma_Ft._Karishma_Sharma_Vikram_Singh___Official_Video(MP3_160K).mp3',
'Tera_Hone_Laga_Hoon_Lyrical_-_Ajab_Prem_Ki_Ghazab_Kahani_Atif_Aslam_Ranbir__Katrina_K___Pritam(MP3_160K).mp3',
'Teri_Aankhon_Mein_Song_Divya_K_Darshan_R__Neha_K___Pearl_V_Manan_B___Radhika__Vinay___Bhushan_K(MP3_160K).mp3',
'The_Chainsmokers_-_Dont_Let_Me_Down_(Official_Video)_ft._Daya(MP3160K).mp3',
'The_Thrust_Boys_Song(MP3160K).mp3',
'The_Weeknd_-_Starboy_ft._Daft_Punk_(Official_Video)(MP3160K).mp3',
'Tujhse_Naraz_Nahi_Zindagi_Female_Cover_Sanam_Lata_Mangeshkar_Hits_Old_Hindi_Songs_version(MP3_160K).mp3',
'Tungevaag_Raaban_-_Bad_Boy_(Official_Video)(MP3160K).mp3',
'Tutu_x_Copines(MP3160K).mp3',
'Two_Feet_-_Go_Fck_Yourself_[Bass_Boosted](MP3160K).mp3',
'U_Turn_-_The_Karma_Theme_(Telugu)_-_Samantha_Anirudh_Ravichander_Pawan_Kumar(MP3_160K).mp3',
'Undipova_Full_Video_Song_Savaari_movie_Song____Shekar_Chandra____Nandu__Priyanka_Sharma(MP3_160K).mp3',
'VTORNIK_-_Money_Rain_(Phonk_Remix)_[Lyrics](MP3160K).mp3',
'Vengaboys_-_To_Brazil_(Karaoke)(MP3160K).mp3',
'Viral_Meme_Songs_2021_Songs_You_Probably_Dont_Know_the_Name___Trending_Songs___Reels___Instagram(MP3_160K).mp3',
'Witt_Lowry_-_Into_Your_Arms_(Lyrics)_ft._Ava_Max_-_[No_Rap](MP3160K).mp3',
'Yemaaya_Chesave_-_Ee_Hridayam_Telugu_Video_Naga_Chaitanya_Samantha(MP3_160K).mp3',
'ZAYN_-_Dusk_Till_Dawn_(Official_Video)_ft._Sia(MP3160K).mp3',
'gone_x_Falak_Tak_Remix_-_DJ_Zedi_Tashan_Akshay_Kumar___Kareena_Kapoor__New_latest_Remix(MP3_160K).mp3',
'maafkan_x_Akon_Right.mp3'
];

function App() {
 var bb = [];
 lis.forEach((zz) => {
    var c = new Audio(`./music/${zz}`);
    var rI = "https://source.unsplash.com/random";
    bb.push(<Box az={c} ay={zz} rI={rI} />)
 })
  return (
    <div className="App">
        {bb}
    </div>
  );
}

export default App;
